config/routes.rb
Rails.application.routes.draw do
  resources :statistics
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/statistic.rb
class Statistic < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
  before_action :set_statistic, only: [:show, :edit, :update, :destroy]

  # GET /statistics
  # GET /statistics.json
  def index
    @statistics = Statistic.all
  end

  # GET /statistics/1
  # GET /statistics/1.json
  def show
  end

  # GET /statistics/new
  def new
    @statistic = Statistic.new
  end

  # GET /statistics/1/edit
  def edit
  end

  # POST /statistics
  # POST /statistics.json
  def create
    @statistic = Statistic.new(statistic_params)

    respond_to do |format|
      if @statistic.save
        format.html { redirect_to @statistic, notice: 'Statistic was successfully created.' }
        format.json { render :show, status: :created, location: @statistic }
      else
        format.html { render :new }
        format.json { render json: @statistic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statistics/1
  # PATCH/PUT /statistics/1.json
  def update
    respond_to do |format|
      if @statistic.update(statistic_params)
        format.html { redirect_to @statistic, notice: 'Statistic was successfully updated.' }
        format.json { render :show, status: :ok, location: @statistic }
      else
        format.html { render :edit }
        format.json { render json: @statistic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statistics/1
  # DELETE /statistics/1.json
  def destroy
    @statistic.destroy
    respond_to do |format|
      format.html { redirect_to statistics_url, notice: 'Statistic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_statistic
      @statistic = Statistic.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def statistic_params
      params.require(:statistic).permit(:date, :total_infected, :daily_infected, :total_died, :daily_died, :intubated, :intensive_care, :total_test, :daily_test, :total_recovered, :daily_recovered)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/statistics_helper.rb
module StatisticsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Covid19Turkey</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/statistics/_form.html.erb
<%= form_with(model: statistic, local: true) do |form| %>
  <% if statistic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(statistic.errors.count, "error") %> prohibited this statistic from being saved:</h2>

      <ul>
      <% statistic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :total_infected %>
    <%= form.number_field :total_infected %>
  </div>

  <div class="field">
    <%= form.label :daily_infected %>
    <%= form.number_field :daily_infected %>
  </div>

  <div class="field">
    <%= form.label :total_died %>
    <%= form.number_field :total_died %>
  </div>

  <div class="field">
    <%= form.label :daily_died %>
    <%= form.number_field :daily_died %>
  </div>

  <div class="field">
    <%= form.label :intubated %>
    <%= form.number_field :intubated %>
  </div>

  <div class="field">
    <%= form.label :intensive_care %>
    <%= form.number_field :intensive_care %>
  </div>

  <div class="field">
    <%= form.label :total_test %>
    <%= form.number_field :total_test %>
  </div>

  <div class="field">
    <%= form.label :daily_test %>
    <%= form.number_field :daily_test %>
  </div>

  <div class="field">
    <%= form.label :total_recovered %>
    <%= form.number_field :total_recovered %>
  </div>

  <div class="field">
    <%= form.label :daily_recovered %>
    <%= form.number_field :daily_recovered %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/statistics/edit.html.erb
<h1>Editing Statistic</h1>

<%= render 'form', statistic: @statistic %>

<%= link_to 'Show', @statistic %> |
<%= link_to 'Back', statistics_path %>

app/views/statistics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Statistics</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Total infected</th>
      <th>Daily infected</th>
      <th>Total died</th>
      <th>Daily died</th>
      <th>Intubated</th>
      <th>Intensive care</th>
      <th>Total test</th>
      <th>Daily test</th>
      <th>Total recovered</th>
      <th>Daily recovered</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @statistics.each do |statistic| %>
      <tr>
        <td><%= statistic.date %></td>
        <td><%= statistic.total_infected %></td>
        <td><%= statistic.daily_infected %></td>
        <td><%= statistic.total_died %></td>
        <td><%= statistic.daily_died %></td>
        <td><%= statistic.intubated %></td>
        <td><%= statistic.intensive_care %></td>
        <td><%= statistic.total_test %></td>
        <td><%= statistic.daily_test %></td>
        <td><%= statistic.total_recovered %></td>
        <td><%= statistic.daily_recovered %></td>
        <td><%= link_to 'Show', statistic %></td>
        <td><%= link_to 'Edit', edit_statistic_path(statistic) %></td>
        <td><%= link_to 'Destroy', statistic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Statistic', new_statistic_path %>

app/views/statistics/new.html.erb
<h1>New Statistic</h1>

<%= render 'form', statistic: @statistic %>

<%= link_to 'Back', statistics_path %>

app/views/statistics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @statistic.date %>
</p>

<p>
  <strong>Total infected:</strong>
  <%= @statistic.total_infected %>
</p>

<p>
  <strong>Daily infected:</strong>
  <%= @statistic.daily_infected %>
</p>

<p>
  <strong>Total died:</strong>
  <%= @statistic.total_died %>
</p>

<p>
  <strong>Daily died:</strong>
  <%= @statistic.daily_died %>
</p>

<p>
  <strong>Intubated:</strong>
  <%= @statistic.intubated %>
</p>

<p>
  <strong>Intensive care:</strong>
  <%= @statistic.intensive_care %>
</p>

<p>
  <strong>Total test:</strong>
  <%= @statistic.total_test %>
</p>

<p>
  <strong>Daily test:</strong>
  <%= @statistic.daily_test %>
</p>

<p>
  <strong>Total recovered:</strong>
  <%= @statistic.total_recovered %>
</p>

<p>
  <strong>Daily recovered:</strong>
  <%= @statistic.daily_recovered %>
</p>

<%= link_to 'Edit', edit_statistic_path(@statistic) %> |
<%= link_to 'Back', statistics_path %>